# This workflow will build and run the tests in a Java project with Gradle
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Run tests in project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Gradle
        id: cache-gradle
        uses: actions/cache@v3
        with:
          path: ./gradle/
          key: ${{ runner.os }}-gradle
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew check
